### ISSUE TITLE
Support Python 3.11 and ibm_db version 3.2.0

### ISSUE THREAD

**Issue by rredburn** [conda-forge/ibm_db-feedstock#60]
### Comment:

My miniforge3 Python 3.11 environments currently can't use ibm_db, not sure why it's restricted to <= 3.10.  Can 3.11 support be added?  Could also update to latest ibm_db version.

**Comment by rredburn** [comment]
@SabaKauser @amukherjee28 @xhochy  is this the right place for these discussions?  Python 3.12 is nearly production, seems like 3.11 is long overdue.

**Comment by xhochy** [comment]
Please fix the PRs that werw opened by the bot if you want to get this forward. There is no need to discuss things, we just need to fix them 😉

**Comment by rredburn** [comment]
If I had any idea how this infrastructure worked I would, but the repo content is greek to me and I can't prioritize learning currently (errors are ppc64le only? how would one debug that without a machine?).  There are three maintainers listed in the readme -- if this is now unmaintained, maybe just mark it as such and put out a call for help.  I'm sure it's a volunteer effort, I hope I don't appear demanding/ungrateful, thanks for your efforts.

**Comment by xhochy** [comment]
Uploaded.
